// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerminoLo.Data;

namespace TerminoLo.Data.Migrations
{
    [DbContext(typeof(TerminoLoDbContext))]
    [Migration("20200524173529_TermDBS001")]
    partial class TermDBS001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TerminoLo.Data.Begriff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bemerkungen")
                        .HasMaxLength(1000);

                    b.Property<string>("Hauptbenennung")
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.Property<string>("TagListe")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Begriffe");
                });
#pragma warning restore 612, 618
        }
    }
}
